CREATE TABLE IF NOT EXISTS users (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE	,
	user_name VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	price DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS products_stock (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	product_id INT(11) NOT NULL,
	FOREIGN KEY (product_id) REFERENCES products(id),
	quantity INT(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS admins (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT(11) NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS api_tokens (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT(11) NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id),
	token VARCHAR(255) NOT NULL
);