CREATE TABLE IF NOT EXISTS users (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	price DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS products_stock (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	product_id INT(11) NOT NULL,
	FOREIGN KEY (product_id) REFERENCES products(id),
	quantity INT(11) NOT NULL
);